# Welcome {.unnumbered}

This Quarto book serves as a user tutorial for the `fdid` package in R, which implements the **Factorial Difference-in-Differences (FDID)** framework introduced by @xu2026factorial\[<a href="https://yiqingxu.org/papers/2025_fdid/fdid.pdf" target="_blank">Paper</a>\]. This design is tailored for panel data settings where all units are exposed to a universal event but vary in a baseline factor $G$ (currently supported as binary).

`fdid` provides two main functions:

-   `fdid_prepare()`: reshapes long format panel data into a wide `fdid()`-ready format.
-   `fdid()`: performs factorial difference-in-differences estimation using several methods.

And two S3 methods:

-   `summary()`: summarizes the estimation results.
-   `plot()`: visualizes raw means, dynamic effects, and model comparisons.

## Organization

The user tutorial is structured into the following chapters:

-   [Chapter @sec-start]\
    This chapter covers installation instructions and introduces the dataset.

-   [Chapter @sec-main]\
    This chapter explains how to prepare the dataset, perform factorial difference-in-differences estimation using several methods and plot the results.

-   [Chapter @sec-visualization]\
    This chapter explores more various plotting options.

## Contributors

-   [Yiqing Xu](https://yiqingxu.org/){target="_blank"}\
-   [Rivka Lipkovitz](https://rivka.me/){target="_blank"}(Undergraduate at MIT)\
-   [Enhan Liu](https://enhan-liu.github.io/){target="_blank"} (Master student at UChicago Harris)
