---
title: "FDID Package Demonstration"
author: "Rivka Lipkovitz"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example 1: Test on Cao et al. (2022)

```{r example1-setup}
# Load the FDID package and other necessary packages
library(fdid)
library(readstata13)

# Load the dataset (currently in long-format)
d <- as.data.frame(read.csv("mortality.csv"))

# Data Preparation
d$uniqueid <- paste(as.character(d$provid), as.character(d$countyid), sep = "-")
d$provid <- as.factor(d$provid)
d$highzupu <- ifelse(d$pczupu >= median(d$pczupu, na.rm = TRUE), 1, 0)

# Define common parameters 
tr_period <- 1958:1961
ref_period <- 1954:1957
treat <- "highzupu" 
Y <- "mortality"  
time <- "year"
unit <- "uniqueid"
covar <- c("avggrain", "nograin", "urban", "dis_bj", "dis_pc",
           "rice", "minority", "edu", "lnpop")
```

### Data Preparation

```{r example1-data-preparation}
prepared_data <- fdid_prepare(
  data = d,
  Y_label = Y,
  X_labels = covar,
  G_label = treat,
  unit_label = unit,
  time_label = time
)
cat("Prepared Data Summary:\n")
str(prepared_data)
```

### FDID Estimation

```{r example1-fdid-estimation}
# FDID estimation with DID
fdid_results_did <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "did",
  vartype = "robust",
)
cat("FDID Results Summary (DID):\n")
summary(fdid_results_did)

# FDID estimation with OLS1
fdid_results_ols1 <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols1",
  vartype = "robust"
)
cat("FDID Results Summary (OLS1):\n")
summary(fdid_results_ols1)

# FDID estimation with OLS2
fdid_results_ols2 <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols2",
  vartype = "robust"
)
cat("FDID Results Summary (OLS2):\n")
summary(fdid_results_ols2)

# FDID estimation with OLS2 and targetting ATT
fdid_results_ols2 <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols2",
  vartype = "robust",
  ATT = TRUE
)
cat("FDID Results Summary (Targetting ATT with OLS2):\n")
summary(fdid_results_ols2)

# FDID with Entropy Balancing
fdid_results_ebal <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ebal",
  vartype = "robust",
  ATT = TRUE
)
cat("FDID Results Summary (Entropy Balancing):\n")
summary(fdid_results_ebal)

# FDID with AIPW
fdid_results_aipw <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "aipw",
  vartype = "robust"
)
cat("FDID Results Summary (AIPW):\n")
summary(fdid_results_aipw)

# OLS1 parallel computation with jackknife variance
fdid_results_ols1_jack_parallel <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols1",
  vartype = "jackknife",
  parallel = TRUE,
  cores = 6,
  nsims = 100
)
cat("FDID Results Summary (OLS1 Parallel Jackknife):\n")
summary(fdid_results_ols1_jack_parallel)

# OLS2 parallel computation with jackknife variance
fdid_results_ols2_jack_parallel <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols2",
  vartype = "jackknife",
  parallel = TRUE,
  cores = 6,
  nsims = 100
)
cat("FDID Results Summary (OLS2 Parallel Jackknife):\n")
summary(fdid_results_ols2_jack_parallel)

# OLS1 parallel computation with bootstrap variance
fdid_results_ols1_boot_parallel <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols1",
  vartype = "bootstrap",
  parallel = TRUE,
  cores = 6,
  nsims = 100
)
cat("FDID Results Summary (OLS1 Parallel Bootstrap):\n")
summary(fdid_results_ols1_boot_parallel)

# OLS2 parallel computation with bootstrap variance
fdid_results_ols2_boot_parallel <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols2",
  vartype = "bootstrap",
  parallel = TRUE,
  cores = 6,
  nsims = 100
)
cat("FDID Results Summary (OLS2 Parallel Bootstrap):\n")
summary(fdid_results_ols2_boot_parallel)
```

### Visualization

```{r example1-visualization}
# Raw means plot
plot(fdid_results_ols1, type = "raw")

# Dynamic effects plot
plot(fdid_results_ols1, type = "dynamic")

# Propensity score overlap
plot(fdid_results_aipw, type = "overlap")

# Comparison of estimates
plot(fdid_list(fdid_results_did, fdid_results_ols1, fdid_results_ols2, fdid_results_ebal, fdid_results_aipw))
```

## Example 2: Replication of Chen et al. (2024) 

```{r example2-setup}
# Load the dataset (currently in long-format)
d <- read.dta13("Table1.dta")

# Data Preparation
wubaos <- names(tapply(d$stronghold_reform, d$prefecture_id, mean)
                [tapply(d$stronghold_reform, d$prefecture_id, mean)>0])
d$wubao <- ifelse(d$prefecture_id %in% wubaos, 1, 0)

d$uniqueid <- paste(as.character(d$prov_id), as.character(d$prefecture_id), sep = "-")
d$prefecture_id = factor(d$prefecture_id)

# Define common parameters
tr_period <- 8:12
ref_period = 2:7
treat <- "wubao" 
Y <- "arist_recruit" 
time <- "emperor_id"
unit <- "uniqueid"
cluster <- "prefecture_id"
```

### Plots look the same

```{r example2-output}
prepared_data <- fdid_prepare(
  data = d,
  Y_label = Y,
  X_labels = NULL,
  G_label = treat,
  unit_label = unit,
  time_label = time,
  cluster_label = cluster
)
fdid_results_ols1 <- fdid(
  s = prepared_data,
  tr_period = tr_period,
  ref_period = ref_period,
  method = "ols1",
  vartype = "robust"
)

plot(fdid_results_ols1)
plot(fdid_results_ols1, type="dynamic")
```
